### PR TITLE
Added the question

### PR DESCRIPTION
**Pull request by LukeHarding**
fuck it, I deleted my fork and re cloned it. Then I modded it with the question and now will pull it.

### CODE REVIEW

**Comment by RowdyChildren** [comment]
That is not the point sir

**Comment by RowdyChildren** [comment]
Merged

**Comment by LukeHarding** [comment]
I am on Linux right now I don't have a good place to put repos to rebase code.

**Comment by RowdyChildren** [comment]
Git is native on OS X

**Comment by LukeHarding** [comment]
Restating my prior statement: I am NOT on Linux right now I don't have a good place to put repos to rebase code. I am on my Mac, but this mac is NOT for school programming.

**Comment by RowdyChildren** [comment]
Whatever, I merged your code 20 minutes ago :smile_cat:

**Comment by LukeHarding** [comment]
Yep. True that. Wanna set up a gitlab so we can have a private repo for more sensitive code? I'll host it on a port on my VPS.

**Comment by RowdyChildren** [comment]
sure, we can do that

**Comment by LukeHarding** [comment]
Yay, sharing homework time!!!!

**Comment by RowdyChildren** [comment]
Gotta get that VPN setup first...

**Pull request merged**
